
services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  app:
    build: .
    ports:
      - "8000:8000"


volumes:
  qdrant_data: